defaults:
  - env: jaxnav
  - learning: ippo-jaxnav
  - _self_

"SEED": 2
# "GROUP_NAME": "jaxnav-sfl"
"ENTITY": "evelinawg-university-of-oxford-org"
"PROJECT": "jaxnav-barn"
"WANDB_MODE" : "online"
"SAVE_PATH": "checkpoints/multi_robot_ued"

env:
  num_agents: 1
  test_set: "single"
  env_params:
   map_id: "Grid-Rand-Barn"
   map_params:
    map_size: [30, 30]
    fill: 0.25
    start_pad: 2

learning:
  # "NUM_ENVS": 256  
  "LR": 7e-5
  "NUM_STEPS": 500 #1500
  # "NUM_UPDATES": 15
  "NUM_ENVS_FROM_SAMPLED": 128
  "NUM_ENVS_TO_GENERATE": 128

# SAMPLE LEARNABILITY 
"BATCH_SIZE": 1000
"NUM_BATCHES": 5
"ROLLOUT_STEPS": 3000 #1500
"NUM_TO_SAVE": 100
"EVAL_SAMPLED_SET_PATH": "/home/evelina/sampling-for-learnability/sfl/data/test_sets/barn_test_300_1a.pkl"

# defaults:
#   - env: jaxnav
#   - learning: ippo-jaxnav
#   - _self_

# "SEED": 2
# "GROUP_NAME": "jaxnav-sfl"
# "ENTITY": ""
# "PROJECT": "multi_robot_ued"
# "WANDB_MODE" : "disabled"
# "SAVE_PATH": "checkpoints/multi_robot_ued"

# env:
#   num_agents: 1
#   test_set: "single"

# learning:
#   # "NUM_ENVS": 256
#   "NUM_ENVS_FROM_SAMPLED": 128
#   "NUM_ENVS_TO_GENERATE": 128

# # SAMPLE LEARNABILITY 
# "BATCH_SIZE": 1000
# "NUM_BATCHES": 5
# "ROLLOUT_STEPS": 1000
# "NUM_TO_SAVE": 100
# "EVAL_SAMPLED_SET_PATH": "/home/evelina/sampling-for-learnability/sfl/data/test_sets/sampled_tc_100e_1a.pkl"